### ISSUE TITLE
Version Type Clarificatioion

### ISSUE THREAD

**Issue by kyeliseyev** [criteo/prebid-addressability-framework-proposal#79] opened 2022-02-11 05:37 UTC
Current numeric type of version [here](https://github.com/criteo/addressable-network-proposals/blob/main/mvp-spec/dsp-implementation.md#identity-object) probably will cause problems, e.g.
 * float `1.0` could be rounded into `1`
 * `0.1` could be represented as `0.100000000000000000000001` because of [inaccuracy problems of float format](https://en.wikipedia.org/wiki/Floating-point_arithmetic#Accuracy_problems).

Could you please consider making all version fields string-type, or integer major/integer minor?

**Comment by OlivierChirouze** [comment] 2022-02-11 08:29
Thanks,

I think the issue is wider since we haven't yet clarified the versioning strategy, see https://github.com/criteo/addressable-network-proposals/issues/6

However, as long as we consider having major + minor version numbers, I agree with you a string format is more appropriate.

I created https://github.com/criteo/addressable-network-proposals/pull/80/files to adapt all the existing schemas and "partials" used mainly in the operator API doc.
We plan to also use these files in the DSP docs _soon_, until then give a look at the PR to give me your opinion?

Thanks

**Comment by kyeliseyev** [comment] 2022-02-11 11:17
> We plan to also use these files in the DSP docs soon

If I understand correctly, it's about not paying attention right now, that version field is still numeric in `dsp-implementation.md` in `version-as-string` branch?

I only wonder why you limit the number of digits to one and only one per each version part. Say, I wish you a good luck with the protocol and its applicability, which might cause periodic upgrades and versions like 10.128 in the future. Doesn't pattern like `^[0-9]+\\.[0-9]+$` look more suitable? It's up to you, I'm just curious.

Version type change looks good to me, thanks.

**Comment by OlivierChirouze** [comment] 2022-02-11 13:28
> So, you will fix numeric type of the version in dsp-implementation.md in version-as-string branch, right?

Almost. We will fix dsp-implementation.md when we define all messages as JSON-schema files and update the docs.

> I only wonder why you limit the number of digits to one and only one per each version part

Of course you are right! I just went a little too fast 🤦‍♂️.
Fixed in the PR, thanks!

**Closed** 2022-04-01 10:03 UTC
